def line():
    A = float(input("Ingrese el coeficiente A: "))
    B = float(input("Ingrese el coeficiente B: "))
    X1 = float(input("Ingrese el coeficiente X1: "))
    X2 = float(input("Ingrese el coeficiente X2: "))
    print(f"El coeficiente A de su ecuación de la recta es:", A)
    print(f"El coeficiente B de su ecuación de la recta es:", B)
    print(f"El coeficiente X1 de su ecuación de la recta es:", X1)
    print(f"El coeficiente X2 de su ecuación de la recta es:", X2)
    print(f"\nPara la siguiente ecuación:")
    print(f"\tY = {A}X + {B}")
    P1 = (X1, A*X1 + B)
    P2 = (X2, A*X2 + B)
    print(f"\nDados los siguientes puntos:")
    print(f"\tP1 {P1}")
    print(f"\tP2 {P2}")
    distancia = ((X2 - X1)**2 + ((A*X2 + B) - (A*X1 + B))**2)**0.5
    print(f"\nLa distancia entre ellos es:", distancia)
